version: "3.4"

#sudo docker run -d -p 5672:5672 -e RABBITMQ_DEFAULT_USER=saarthi -e RABBITMQ_DEFAULT_PASS=analytics rabbitmq:3-management
services:
#  rabbitmq:
#    image:  rabbitmq:3-management
#    container_name: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: saarthi
#      RABBITMQ_DEFAULT_PASS: analytics
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  analytics-aadhar-english:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer.py
      - --endpoints
      - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english1:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english2:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english3:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english4:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english5:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
  # analytics-aadhar-english6:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml
    
  # analytics-aadhar-english7:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml

  # analytics-aadhar-english8:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml

  # analytics-aadhar-english9:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml

  # analytics-aadhar-english10:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml

  # analytics-aadhar-english11:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core.yml

  
  analytics-aadhar-hindi:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer-hindi.py
      - --endpoints
      - constants/emi_english/endpoints_core_hindi.yml

  # analytics-aadhar-hindi1:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml
  # analytics-aadhar-hindi2:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml
  # analytics-aadhar-hindi3:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml
  # analytics-aadhar-hindi4:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml
  # analytics-aadhar-hindi5:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml

  # analytics-aadhar-hindi6:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml

  # analytics-aadhar-hindi7:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi8:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi9:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi10:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml

  # analytics-aadhar-hindi11:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi12:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi12:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml



  # analytics-aadhar-hindi13:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi14:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi15:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml


  # analytics-aadhar-hindi16:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-hindi.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_hindi.yml
    
  analytics-aadhar-kannada:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer-kannada.py
      - --endpoints
      - constants/emi_english/endpoints_core_kannada.yml
  # analytics-aadhar-kannada1:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-kannada.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_kannada.yml
  # analytics-aadhar-kannada2:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-kannada.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_kannada.yml
  # analytics-aadhar-kannada3:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-kannada.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_kannada.yml
  # analytics-aadhar-kannada4:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #     - ./constants:/app/constants
  #     - ./analytics:/app/analytics
  #     - ./call_logs.csv:/app/call_logs.csv
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   network_mode: "host"
  #   command:
  #     - analytics/pika-consumer-kannada.py
  #     - --endpoints
  #     - constants/emi_english/endpoints_core_kannada.yml

  analytics-aadhar-malayalam:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer-malayalam.py
      - --endpoints
      - constants/emi_english/endpoints_core_malayalam.yml


  analytics-aadhar-telugu:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer-telugu.py
      - --endpoints
      - constants/emi_english/endpoints_core_telugu.yml

  analytics-aadhar-tamil:
    image: "tatisudheer/chatbot"
    volumes:
      - ./constants:/app/constants
      - ./analytics:/app/analytics
      - ./call_logs.csv:/app/call_logs.csv
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    command:
      - analytics/pika-consumer-tamil.py
      - --endpoints
      - constants/emi_english/endpoints_core_tamil.yml



